apiVersion: v1
kind: ServiceAccount
metadata:
  name: lumi-runtime
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: lumi-sandbox-controller
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: lumi-sandbox-child
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: lumi-migration
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: lumi-sandbox-job-controller
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: lumi-sandbox-job-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: lumi-sandbox-job-controller
subjects:
  - kind: ServiceAccount
    name: lumi-sandbox-controller
    namespace: lumi-staging
