"""LUMI domain semantics.

This package intentionally depends only on Python standard-library types. ORM,
HTTP, provider SDKs, LangGraph checkpoints, and persistence details belong in
adapter/application layers.
"""

from .entities import (
    AgentRun,
    Artifact,
    ArtifactVersion,
    Asset,
    Branch,
    Brand,
    CostEntry,
    CostEntryKind,
    DesignDocument,
    Generation,
    Organization,
    OrganizationStatus,
    Project,
    Task,
    Workspace,
)
from .errors import DomainError, InvalidTransition, InvariantViolation
from .ids import new_uuid7
from .invariants import (
    require_artifact_lineage_acyclic,
    require_same_organization,
    require_task_graph_acyclic,
)
from .states import (
    AgentRunStatus,
    ArtifactVersionStatus,
    GenerationStatus,
    ProjectStatus,
    TaskStatus,
)
from .value_objects import (
    Budget,
    Color,
    Dimensions,
    DimensionUnit,
    MimeType,
    ModelRef,
    Money,
    OperationIdentity,
    Point,
    ProviderRef,
    Rect,
    RightsLevel,
    RightsPolicy,
    StorageRef,
    Transform,
    Usage,
    VersionRef,
)

__all__ = [
    "AgentRun",
    "AgentRunStatus",
    "Artifact",
    "ArtifactVersion",
    "ArtifactVersionStatus",
    "Asset",
    "Branch",
    "Brand",
    "Budget",
    "Color",
    "CostEntry",
    "CostEntryKind",
    "DesignDocument",
    "Dimensions",
    "DimensionUnit",
    "DomainError",
    "Generation",
    "GenerationStatus",
    "InvalidTransition",
    "InvariantViolation",
    "MimeType",
    "ModelRef",
    "Money",
    "OperationIdentity",
    "Organization",
    "OrganizationStatus",
    "Point",
    "Project",
    "ProjectStatus",
    "ProviderRef",
    "Rect",
    "RightsLevel",
    "RightsPolicy",
    "StorageRef",
    "Task",
    "TaskStatus",
    "Transform",
    "Usage",
    "VersionRef",
    "Workspace",
    "new_uuid7",
    "require_artifact_lineage_acyclic",
    "require_same_organization",
    "require_task_graph_acyclic",
]
