from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "contracts/design-ir/v1/type-manifest.json"
PY_TARGET = ROOT / "contracts/design-ir/v1/generated/types.py"
TS_TARGET = ROOT / "contracts/design-ir/v1/generated/types.ts"


def _quoted(values: list[str]) -> str:
    return ", ".join(json.dumps(value) for value in values)


def render_python(manifest: dict[str, object]) -> str:
    node_kinds = list(manifest["node_kinds"])
    semantic_roles = list(manifest["semantic_roles"])
    operation_types = list(manifest["operation_types"])
    return (
        "# Generated by scripts/generate_design_ir_types.py. DO NOT EDIT.\n"
        "from __future__ import annotations\n\n"
        "from typing import Any, Literal, TypedDict\n\n"
        f"SCHEMA_VERSION = {manifest['schema_version']!r}\n"
        f"RANGE_INDEXING = {manifest['range_indexing']!r}\n"
        f"CANONICALIZATION = {manifest['canonicalization']!r}\n\n"
        f"type NodeKind = Literal[{_quoted(node_kinds)}]\n"
        f"type SemanticRole = Literal[{_quoted(semantic_roles)}]\n"
        f"type OperationType = Literal[{_quoted(operation_types)}]\n\n"
        "class DesignIRTransform(TypedDict):\n"
        "    x: float\n    y: float\n    width: float\n    height: float\n"
        "    rotation_deg: float\n    scale_x: float\n    scale_y: float\n"
        "    skew_x: float\n    skew_y: float\n    anchor_x: float\n    anchor_y: float\n\n"
        "class DesignIRNode(TypedDict, total=False):\n"
        "    id: str\n    kind: NodeKind\n    name: str\n    role: str\n"
        "    parent_id: str | None\n    children: list[str]\n    visible: bool\n"
        "    locked: bool\n    opacity: float\n    blend_mode: str\n"
        "    transform: DesignIRTransform\n    bounds: dict[str, float]\n"
        "    style_refs: list[str]\n    constraint_refs: list[str]\n"
        "    semantic: dict[str, Any]\n    metadata: dict[str, Any]\n\n"
        "class DesignIRDocument(TypedDict):\n"
        "    schema_version: str\n    document_id: str\n    unit: str\n    root_id: str\n"
        "    nodes: dict[str, DesignIRNode]\n    resources: dict[str, dict[str, Any]]\n"
        "    metadata: dict[str, Any]\n\n"
        "class DesignOperation(TypedDict):\n"
        "    operation_id: str\n    type: OperationType\n    target_ids: list[str]\n"
        "    expected_document_version: int\n    payload: dict[str, Any]\n    reason: str\n"
    )


def render_typescript(manifest: dict[str, object]) -> str:
    node_kinds = list(manifest["node_kinds"])
    semantic_roles = list(manifest["semantic_roles"])
    operation_types = list(manifest["operation_types"])
    union = lambda values: " | ".join(json.dumps(value) for value in values)
    return (
        "// Generated by scripts/generate_design_ir_types.py. DO NOT EDIT.\n"
        f"export const DESIGN_IR_SCHEMA_VERSION = {json.dumps(manifest['schema_version'])} as const;\n"
        f"export const DESIGN_IR_RANGE_INDEXING = {json.dumps(manifest['range_indexing'])} as const;\n"
        f"export const DESIGN_IR_CANONICALIZATION = {json.dumps(manifest['canonicalization'])} as const;\n\n"
        f"export type NodeKind = {union(node_kinds)};\n"
        f"export type SemanticRole = {union(semantic_roles)};\n"
        f"export type OperationType = {union(operation_types)};\n\n"
        "export interface DesignIRTransform {\n"
        "  x: number; y: number; width: number; height: number; rotation_deg: number;\n"
        "  scale_x: number; scale_y: number; skew_x: number; skew_y: number;\n"
        "  anchor_x: number; anchor_y: number;\n}\n\n"
        "export interface DesignIRNode {\n"
        "  id: string; kind: NodeKind; name: string; role: SemanticRole | `custom:${string}`;\n"
        "  parent_id: string | null; children: string[]; visible: boolean; locked: boolean;\n"
        "  opacity: number; blend_mode: string; transform: DesignIRTransform;\n"
        "  bounds: Record<string, number>; style_refs: string[]; constraint_refs: string[];\n"
        "  semantic: Record<string, unknown>; metadata: Record<string, unknown>;\n"
        "  [key: string]: unknown;\n}\n\n"
        "export interface DesignIRDocument {\n"
        "  schema_version: typeof DESIGN_IR_SCHEMA_VERSION; document_id: string; unit: \"px\";\n"
        "  root_id: string; nodes: Record<string, DesignIRNode>;\n"
        "  resources: Record<string, Record<string, unknown>>; metadata: Record<string, unknown>;\n}\n\n"
        "export interface DesignOperation {\n"
        "  operation_id: string; type: OperationType; target_ids: string[];\n"
        "  expected_document_version: number; payload: Record<string, unknown>; reason: string;\n}\n\n"
        "export function codePointLength(value: string): number { return Array.from(value).length; }\n"
        "export function sliceCodePoints(value: string, start: number, end: number): string {\n"
        "  return Array.from(value).slice(start, end).join(\"\");\n}\n"
    )


def _write_or_check(path: Path, expected: str, check: bool) -> None:
    if check:
        actual = path.read_text(encoding="utf-8") if path.exists() else None
        if actual != expected:
            raise SystemExit(f"generated Design IR type drift: {path.relative_to(ROOT)}")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(expected, encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    _write_or_check(PY_TARGET, render_python(manifest), args.check)
    _write_or_check(TS_TARGET, render_typescript(manifest), args.check)


if __name__ == "__main__":
    main()
